### ISSUE TITLE
Custom Controls does not exist

### ISSUE THREAD

**Issue by danielleevandenbosch** [gojimmypi/crMailer#1]
Hey there, 
I am looking for the custom controls package.  I have the yellow triangle next to it in my solution. Might you have them?

**Comment by gojimmypi** [comment]
Hey there & thanks for checking out my crMailer app. Good find on the missing reference. 

The CustomControls is an old, legacy library that I'm working on removing. It's not needed for this app; it was a leftover from when I ported the code from my ASPX library that renders a report in a web page. 

I've pushed [a change that removes it](https://github.com/gojimmypi/crMailer/commit/02ba3b02eaed784fb10e0f184363d3ceb21b40b4#diff-431dbcaed092fbdfb96e4df11af098226d0de9676c87cc5b71046517169b50c8L97) from the project file. Does that work for you?

Also note that I typically checkout items to `\workspace\` and the precompiled binaries such as the CR runtime DLLs are in `\workspace\bin64` (I typically compile to x64 rather than MSIL). I've also changed the project file to more properly reflect this, as the hint path was one `..\` too far.

**Comment by danielleevandenbosch** [comment]
Yeah that should work. Thanks for making this thing

**Comment by gojimmypi** [comment]
Cool. I hope you find it useful.

**Comment by gojimmypi** [comment]
Hi @danielleevandenbosch just wondering if you've been able to get this crMailer to work in your environment? I noticed at the day job I left myself a note in the readme about a possible cached data issue with `Save data with report` turned on. See #2
